version: "4.10"

networks:
  server:
    driver: bridge

services:
  php:
    restart: always
    build:
      context: ".docker/"
    ports:
      - "80:80"
    volumes:
      - /var/www/html
    networks:
      - server



  db:
    image: "postgres:14.4"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: blog

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'


