FROM php:8.1.8-apache

#COPY src/ /var/www/your_domain/

RUN apt-get update && \
    apt-get install -y libpq-dev && \
    docker-php-ext-install pdo pdo_pgsql pgsql
COPY . /var/www/html
WORKDIR /var/www/html
